#ifndef __CGA2PDB_PRO__
#define __CGA2PDB_PRO__
 
/*
   Prototypes for directory : CGA2PDB
   Generated by pimmsccs on Tue Nov  3 13:48:08 GMT 1992
*/
 
void CGAInsCoord(char *RefPDB, short updtClg);
 
void CGAReadBlock(int BlockNum);
 
void CGAReadHdr(char *CGAName);
 
void CGARenPDB(char *OldName, short renClg);
 
void CGAUpdtClg(char *ClgPDB);
 
void cga2pdbmain(int argc, char *argv[]);
 
 
#endif
