CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     CPRINT
C     ACRM 13.06.91
C     Replaces writes to channel 6 with C i/o
      SUBROUTINE CPRINT(STRING)
      CHARACTER*(*) STRING
      CALL CPRINT1(%REF(STRING),LEN(STRING))
      RETURN
      END
