#ifndef __EUREKAF_PRO__
#define __EUREKAF_PRO__
 
/*
   Prototypes for directory : EUREKAF
   Generated by pimmsccs on Tue Nov  3 13:50:22 GMT 1992
*/
 
FINT4 eureni (FINT4 * mols , FINT4 * force );
 
void eurext ( );
 
void eurost (FINT4 * test , FINT4 * final , FINT4 * iters , FINT4 * cycles , FINT4 * func );
 
 
#endif
