CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     FILLLOG
C     ACRM 24.06.91
C     Fills an array with logicals
      SUBROUTINE FILLLOG(ARR,NUM,TRUTH)
      LOGICAL ARR(*), TRUTH
      INTEGER NUM, I
      DO 100 I = 1, NUM
         ARR(I) = TRUTH
  100 CONTINUE
      RETURN
      END
