CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     Recoded ACRM 12.06.91
      REAL FUNCTION MAXR(ARRAY,NUM)
      REAL ARRAY(*)
      INTEGER NUM, I
 
      MAXR = ARRAY(1)
      DO 100 I = 2, NUM
         IF (ARRAY(I).GT.MAXR) MAXR = ARRAY(I)
  100 CONTINUE
      RETURN
      END
