#ifndef __PDB2CGA_PRO__
#define __PDB2CGA_PRO__
 
/*
   Prototypes for directory : PDB2CGA
   Generated by pimmsccs on Tue Nov  3 13:54:40 GMT 1992
*/
 
void CGACopyHdr(FILE *OutputFilePtr, char *CGAName);
 
void CGACopyPDB(FILE *OutputFilePtr, char *Loop, int ThisPDB);
 
int CGAReadLine(FILE *FilePtr, char *Line);
 
void pdb2cgamain(int argc, char *argv[]);
 
 
#endif
